### ISSUE TITLE
Help wanted to specify the correct API_Polar for a decoder

### ISSUE THREAD

**Issue by wheberth** [aff3ct/my_project_with_aff3ct#1]
Hi all, 

We are integrating the AFF3CT library in OOT GNURadio block for a realtime communication chain.
We have already it running but I am not sure about how specify the the API_polar for the decoder.
In order to achieve a good throughput We have generated a fully unrolled decoder and I am instantiating it to work with int8 LLR's. 

`module::Decoder_polar_SC_fast_sys_N2048_K1024_SNR0<int8_t, int8_t, API_polar_static_intra_8bit<int8_t, int8_t>>`

That would be the correct API_polar type to use with quantized LLRs with 6 bits and decimal position at bit 1?

**Comment by kouchy** [comment]
Hi @wheberth,

If you generated an unrolled decoder with the [polar_decoder_gen](https://github.com/aff3ct/polar_decoder_gen) project, yes you are using the most efficient `API_polar`. And yes the [6,1] quantization is good, you should not notice significant performance degradation.

I hope it helps.

**Comment by wheberth** [comment]
Hi @kouchy, 
Thank you for your answer. Yes, it helped, but even using the decoder generated with the [polar_decoder_gen](https://github.com/aff3ct/polar_decoder_gen) we need to specify the API_polar when creating the object. Just one question remaining. How the tell the decoder the decimal position used in the quantizer module?

Best regards,
Wheberth

**Comment by kouchy** [comment]
Yes you need to specify the `API_polar` because the generated code is the same for various datatypes and SIMD strategy. The decoder don't care about the quantization, you do not need to give the decimal position to the decoder. The decoder only performs additions and minimum selections so it can operates without knowing the precise quantization.

**Comment by wheberth** [comment]
Gotcha. 
Thank you very much again.
