### ISSUE TITLE
Bootstrap Example

### ISSUE THREAD

**Issue by marielacbv** [aff3ct/my_project_with_aff3ct#2]
Dear all,

I am trying to modify the decoder in the bootstrap example by initializing a decoder Decode_LDPC_BP_floding_Gallager_A using this code:

> m.decoder = std::unique_ptr<module::Decoder_LDPC_BP_flooding_Gallager_A<>>(new module::Decoder_LDPC_BP_flooding_Gallager_A<>(p.K, p.N, 100, x, y ,z ));

Hoever the other parameters I still do not know who to properly set them. The class has 8 inputs
How shall I add the other parameters @kouchy ?

using this H matrix: conf/dec/LDPC/PureIRA_R_4_5_N20k_H.alist

thanks and regards 

the

**Comment by kouchy** [comment]
Hi @marielacbv,

If you want to use an LDPC decoder I suggest you to use the `Factory` example instead of the `Bootstrap` one (see the documentation: https://aff3ct.readthedocs.io/en/development/user/library/library.html#factory). At this time I also encourage you to use the `development` branch of the `my_project_with_aff3ct` as there is significant simplifications from the `master` branch.

If you use the `Factory` example as a start point you only have to replace `repetition` by `LDPC` in the `main.cpp`.

Here is an example of command you can try with this the `Factory` example:

```bash
./bin/my_project --dec-h-path ../../../lib/aff3ct/conf/dec/LDPC/PureIRA_R_4_5_N20k_H.alist -N 20480 -K 16384 -D BP_FLOODING --dec-implem GALA --src-type AZCW --enc-type AZCW -e 100 -i 20
```

And the following decoding performance I get:
```
# ---------------------||------------------------------------------------------||---------------------
#  Signal Noise Ratio  ||   Bit Error Rate (BER) and Frame Error Rate (FER)    ||  Global throughput  
#         (SNR)        ||                                                      ||  and elapsed time   
# ---------------------||------------------------------------------------------||---------------------
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
#     Es/N0 |    Eb/N0 ||      FRA |       BE |       FE |      BER |      FER ||  SIM_THR |    ET/RT 
#      (dB) |     (dB) ||          |          |          |          |          ||   (Mb/s) | (hhmmss) 
# ----------|----------||----------|----------|----------|----------|----------||----------|----------
      -0.97 |     0.00 ||      127 |  1046834 |      127 | 5.03e-01 | 1.00e+00 ||    1.227 | 00h00'01   
       0.03 |     1.00 ||      125 |  1022892 |      125 | 4.99e-01 | 1.00e+00 ||    1.255 | 00h00'01   
       1.03 |     2.00 ||      126 |  1032000 |      126 | 5.00e-01 | 1.00e+00 ||    1.262 | 00h00'01   
       2.03 |     3.00 ||      122 |   997853 |      122 | 4.99e-01 | 1.00e+00 ||    1.237 | 00h00'01   
       3.03 |     4.00 ||      120 |   978731 |      120 | 4.98e-01 | 1.00e+00 ||    1.248 | 00h00'01   
       4.03 |     5.00 ||      131 |  1070718 |      131 | 4.99e-01 | 1.00e+00 ||    1.294 | 00h00'01   
       5.03 |     6.00 ||      122 |   999019 |      122 | 5.00e-01 | 1.00e+00 ||    1.241 | 00h00'01   
       6.03 |     7.00 ||      131 |  1071871 |      131 | 4.99e-01 | 1.00e+00 ||    1.306 | 00h00'01   
       7.03 |     8.00 ||      168 |   259747 |      123 | 9.44e-02 | 7.32e-01 ||    1.704 | 00h00'01   
       8.03 |     9.00 ||    14165 |    14880 |      106 | 6.41e-05 | 7.48e-03 ||   11.400 | 00h00'20
```

I hope it helps.

**Comment by marielacbv** [comment]
Yes, it helps,

Is there a possible way to turn off the modem?. I noticed that there is a class to turn off the channel, but I can´t find a class for turning off the  modem as I need to test only the decoder 

thank you for this one and the previous comment

**Comment by kouchy** [comment]
I think it is preferable to do not turn off the modem. If you use a BPSK modulator, if fact you are just making the mapping (`0 => 1`, `1 => -1`). Perhaps you want to disable the division by sigma square in the BPSK demodulator? To do that there is a command line argument: ` --mdm-no-sig2` (see https://aff3ct.readthedocs.io/en/latest/user/simulation/parameters/modem/modem.html#mdm-no-sig2).
