### ISSUE TITLE
Encode/Decode BCH codes

### ISSUE THREAD

**Issue by dvlad96** [aff3ct/my_project_with_aff3ct#3]
Hi,

I want to use aff3ct as a library and make a simple BCH encoder/decoder. I used bootstrap as a guideline but when I call m.decoder -> decode_siho(b.LLRs, b.dec_bits) I get a segmentation fault. I am trying to use the Decoder_BCH_fast. I debugged the code with gdb and it seems that the problem is the "alpha_to" vector. When the constructor is called, "alpha_to" vector has the correct number of elements, but when it reaches the _decode method suddenly it has 35139647296722 elements.

Are you aware of this bug and do you know a fix for it?

I have forked my_project_with_aff3ct and replaced the bootstrap src code with mine: https://github.com/fender9669/my_project_with_aff3ct/blob/master/examples/bootstrap/src/main.cpp

Best regards,
Vlad

**Comment by kouchy** [comment]
Hi @fender9669,

There is a problem here: https://github.com/fender9669/my_project_with_aff3ct/blob/d7b57b1b38957eb4cd7e97ec66a47e41e88c0f88/examples/bootstrap/src/main.cpp#L44-L45. The `tools::BCH_polynomial_generator<>(p.N,p.t)` is allocated on the stack and when you get out of the `init_modules` function, it is lost. The BCH encoder and decoder take a reference as input (as you can see here: https://github.com/aff3ct/aff3ct/blob/ba5db0879a6cab5798b8c56355ce740a8f6205bd/include/Module/Encoder/BCH/Encoder_BCH.hpp#L277). Then you should allocate first the BCH polynomial generator on the stack (for instance here: https://github.com/fender9669/my_project_with_aff3ct/blob/d7b57b1b38957eb4cd7e97ec66a47e41e88c0f88/examples/bootstrap/src/main.cpp#L32 you can add `std::unique_ptr<tools::BCH_polynomial_generator<>> GF`).

I hope it helps.

**Comment by dvlad96** [comment]
That did help!

Thanks

**Comment by Divya916947** [comment]
I have the same problem. I am unable to open the link. Could you please repost the link that has the changes?
