### ISSUE TITLE
Turbo Code example

### ISSUE THREAD

**Issue by AtanasRusevPros** [aff3ct/my_project_with_aff3ct#9]
Hello Adrien,

First of all I want to say a big thank you for this magnificent simulation framework! It has been extremely useful for me while learning some of the basics of Turbo Encoding and the comparison with other coding schemes. 
What I currently try to do is practically build separate chain, just encoder and decoder - without the simulation, channel, noise addition, etc. I tried via launcher, defining the encoder through factory, extracting and calling only separate methods. I have been through the example projects, in particular the bootstrap code. I also read the pdf and online based documentation. The multi-layer template structure however prevents me from doing this. As the parameters and application are completely separated, and most of the parameters are passed via some of the template levels it is really hard to debug. So my question is - is there a project already presenting this code uploaded somewhere, forked? Can you give me some basic advices? Do you have such project at your disposal, so that one can download it and directly experiment?

I definitely think that this would be really interesting not only for me, but also for the community, as this would be direct pure application of the encoding and decoding, without the framework part.

Best Regards,
Atanas

**Comment by kouchy** [comment]
Hi @AtanasRusevPros,

I understand you want to separate the transmitter and the receiver.
I think you should not use the launchers to do that. The launchers have been designed specifically for simulation purpose.
However the factories look like a good starting point to simplify the build process of the AFF3CT modules (encoder, decoder, etc.).

To my point of view, it could be interesting for you to take some time to understand the [tasks](https://github.com/aff3ct/my_project_with_aff3ct/blob/development/examples/tasks/src/main.cpp) and [factory](https://github.com/aff3ct/my_project_with_aff3ct/blob/development/examples/factory/src/main.cpp) examples proposed in this repository (these examples are documented here: https://aff3ct.readthedocs.io/en/latest/user/library/examples.html). They are close to the best way to use AFF3CT. Also the [sequence](https://github.com/aff3ct/my_project_with_aff3ct/blob/development/examples/sequencesrc/main.cpp) example is a new way to call the tasks and it is automatically multi-threaded for you (it is interesting if you are targeting higher throughput).

I hope it helps and do not hesitate if you have other questions.
Adrien

**Comment by AtanasRusevPros** [comment]
Hi Adrien,

I know the examples, but so far had been only through the Bootstrap. So I checked out the Factory and Tasks. I can say that they don't serve me exactly... after all I want to explicitly use only the encoder and decoder on a custom set of data. The Factory example also gave me some build errors. In any case the documentation is not very helpful for my purposes (it's purpose is to explain the parameters and basics of the library, for which it is quite good and helped me grasp many of those :) ). I will continue further to work towards setting up my own encoder and decoder chain, which doesn't involve tasks, threads, etc. 

What I initially wanted to do was declare one specific type of Encoder (Turbo, BCJR), then declare corresponding decoder, while potentially be able to define e.g. exact type of interleaver... And simply feed data from one side, get the data on the other end :). In any case the aff3ct was not designed with this purpose... :). So I will see whether I will succeed in my endeavor. If you have any thoughts I will be really grateful :).

BR,
Atanas

**Comment by AtanasRusevPros** [comment]
Hi Adrien, 

I encode with LTE Interleaver, then calling twice Encoder_RSC_generic_sys. 
My decoder is like in the AFF3CT simulation code - Decoder_turbo_fast, with the same interleaver and two times the Decoder_RSC_BCJR_seq_std. 

The Encoder_RSC_generic_sys requires    " if (N - 2 * n_ff !=  2 * K) {throw...}"
The Decoder_turbo requires:   " if (N - (siso_n.tail_length() + siso_i.tail_length()) != K * 3) {...throw...}"
For decoding I call directly the decode_siho. 

I do this all within one frame.

Both requirements are quite different - it looks like the Encoder requires only 2.x times more space, and the Decoder chain expects 3.x size for N. 

I actually tried to keep the decoder parameters synchronized with the encoder by passing them in this construct:

auto decTurboFast = new aff3ct::module::Decoder_turbo_fast<B_32, Q_32>(p.K, p.N_cw, p.n_ite, *lteInterleaverDecoder, *subDec1_RSC_gen_sys, *subDec2_RSC_gen_sys, p.buffered);

So - I expected, that the decoder will automatically be adjusted to the encoder, but this doesn;t work so.

Can you give me some comments / recommendations?

BR,
Atanas

**Comment by AtanasRusevPros** [comment]
Hi Adrien,

I hope you are OK and not heavily under work. Could you take a look to my issue and give me some recommendations?

Thank you!

BR,
Atanas

**Comment by AtanasRusevPros** [comment]
Hi Adrien and all,

After some more debug I could successfully define and call the interleaver, Turbo encoder and Turbo decoder. 

For anyone who may be interested in this issue - the Turbo Encoding currently works by default with Ratio 1/3. So for one set of data, we have one more encoded set and one more interleaved. Each additional part has also tails. Thus e.g. for 2016 bits we encode a message of 6060, resulting in Ratio 1/3. 

What more needs to be done is a set of simple computations which provides the encoders definitions with the correct K, then we have N for each separate encoder (for the current implementation we need two encoders), and for the full frame we have N_cw as show below:

#define DATA_LENGTH_K 2016 // K
#define SINGLE_TAIL_LENGTH 3

#define FRAME_LENGTH_N (DATA_LENGTH_K*2 + 2*SINGLE_TAIL_LENGTH) // N = 4038
#define FRAME_LENGTH_FULL_N_cw (FRAME_LENGTH_N + DATA_LENGTH_K + 2*SINGLE_TAIL_LENGTH) // 6060  // this is equal to N+N-K

The issue can be closed.

BR,
Atanas

**Comment by kouchy** [comment]
Sorry for the latency, good to know that you succeeded alone :-).
